server:
  servlet:
    encoding:
      charset: UTF-8

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: pharmacyCloudSecretKeyForJwtAuthentication2026VeryStrongKey123

logging:
  level:
    org.springframework.security: TRACE
