spring:
  application:
    name: authentication-service

  datasource:
    url: jdbc:mysql://localhost:3307/pos_auth
    username: root
    password: Root@0710
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
       host: localhost
       port: 6379

server:
  port: 8082

jwt:
  secret : pharmacyCloudSecretKeyForJwtAuthentication2026
  access-expiration: 900000        # 15 mins
  refresh-expiration: 604800000    # 7 days

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/